name: Pull request checks

on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Install make
      run: sudo apt -y install make
    - name: Run verification and tests
      run: make lint test cov-exclude-generated
    - name: Report coverage
      uses: codecov/codecov-action@v2.1.0
      with:
        files: ./cover.out
        flags: unittests
        fail_ci_if_error: true        
