name: pull request - e2e tests

#todo: check caching dependencies: https://github.com/actions/cache
on:
  push:
    branches: [ 'main', 'release-*' ]
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:
  e2e-tests:
    name: e2e-tests
    runs-on: ubuntu-latest
    steps:
    - name: install make
      run: sudo apt-get install make
    - name: set up go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: checkout
      uses: actions/checkout@v3
    - name: run end-to-end tests
      run: make tests-e2e
    - name: upload e2e test logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e-logs
        path: e2e-logs