name: Build and push to quay.io
on:
  push:
    branches: [ main ]

env:
  REGISTRY_USER: netobserv+github_ci
  REGISTRY_PASSWORD: ${{ secrets.QUAY_SECRET }}
  REGISTRY: quay.io/netobserv
  IMAGE: netobserv-ebpf-agent
  IMAGE_ORG: netobserv
  TAGS: main

jobs:
  push-image:
    name: push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19']
    steps:
      - name: install make
        run: sudo apt-get install make
      - name: set up go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: checkout
        uses: actions/checkout@v3
      - name: build images
        run: make ci-images-build
      - name: podman login to quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: quay.io
      - name: get short sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: push to quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE }}
          tags: ${{ env.TAGS }} ${{ env.short_sha }}
          registry: ${{ env.REGISTRY }}
      - name: print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"